name: Say hello

on:
  push: 
    branches: 
      - main

jobs: 
  hello_world:
<<<<<<< HEAD
=======
    # Sistema operativo donde va a correr
>>>>>>> 21194190b5feced88d723f80cae4a459d780a080
    runs-on: ubuntu-18.04
    steps: 
      - name: Echo the message
        run: |
          echo "Hola!"
  