name: Say hello

on:
  push:
    branches: [ development ]

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hola!"
      - name: Dime la fecha
        run: date
      - run: ls -l