name: Say hello
 
on: workflow_dispatch
 
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hola!"
      - name: Dime la fecha
        run: date
      - run: ls -l
